<?xml version="1.0" encoding="utf-8" ?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    attributeFormDefault="Unqualified" elementFormDefault="qualified" >
    <xs:element name="ComplaintAndVoiceFromCustomer">
        <xs:complexType> 
            <xs:all>
                <xs:element name="caseType" type="xs: String" /> 
                <xs:element name="ComplainanFullName" >
                    <xs:element name="ComplainantName" > 
                        <xs:element name="prefix" type="xs: String" /> 
                        <xs:element name="firstName" type="xs: String" /> 
                        <xs:element name="middleName" type="xs: String" /> 
                        <xs:element name="lastName" type="xs: String" /> 
                    </xs:element name="ComplainantName"> 
                </xs:element name="ComplainanFullName"> 
                <xs:element name="nationality" type="xs: String" /> 
                <xs:element name="complainantContact"> 
                    <xs:element name="email" type="xs: String" /> 
                    <xs:element name="telephoneNumber" type="xs: String" /> 
                    <xs:element name="faxNumber" type="xs: String" /> 
                </xs:element name="complainantContact"> 
                <xs:element name="contactAddress"> 
                    <xs:element name="contactAddressThailand" > 
                        <xs:element name="address" type="xs: String" /> 
                        <xs:element name="alley" type="xs: String" /> 
                        <xs:element name="road" type="xs: String" /> 
                        <xs:element name="subdistrict" type="xs: String" /> 
                        <xs:element name="district" type="xs: String" /> 
                        <xs:element name="province" type="xs: String" /> 
                        <xs:element name="postalCode" type="xs: String" /> 
                    </xs:element name="contactAddressThailand" > 
                    <xs:element name="contactAddressForeign" > 
                        <xs:element name="addressDetails" type="xs: String" /> 
                        <xs:element name="city" type="xs: String" /> 
                        <xs:element name="stateCountyArea" type="xs: String" /> 
                        <xs:element name="postalCode" type="xs: String" /> 
                        <xs:element name="countryCode" type="xs: String" /> 
                    </xs:element name="contactAddressForeign">  
                </xs:element name="contactAddress">    
                <xs:element name="referencePerson" type="xs: String" /> 
                <xs:element name="referenceAgency" type="xs: String" /> 
                <xs:element name="contactDateType" type="xs: String" /> 
                <xs:element name="incidentDate"> 
                    <xs:element name="startDate" type="xs: Date" /> 
                    <xs:element name="endDate" type="xs: Date" /> 
                </xs:element name="incidentDate" > 
                <xs:element name="incidentInformation"> 
                    <xs:element name="incidentLocation" type="xs: String" /> 
                    <xs:element name="country" type="xs: String" /> 
                    <xs:element name="province" type="xs: String" /> 
                </xs:element name="incidentInformation" > 
                <xs:element name="complaintOpinionComplimentTopics" > 
                    <xs:element name="transportationTopics" type="xs: String" /> 
                    <xs:element name="accommodationTopics" type="xs: String" /> 
                    <xs:element name="tourServiceTopics" type="xs: String" /> 
                    <xs:element name="rentalVehicleTopics" type="xs: String" /> 
                    <xs:element name="serviceAndRestaurantTopics" type="xs: String" /> 
                    <xs:element name="purchasedGoodsTopics" type="xs: String" /> 
                    <xs:element name="tourismAttractionTopics" type="xs: String" /> 
                    <xs:element name="governmentOfficeTopics" type="xs: String" /> 
                    <xs:element name="tatOfficeTopics" type="xs: String" /> 
                    <xs:element name="otherTopics" type="xs: String" /> 
                </xs:element name="complaintOpinionComplimentTopics"> 
                <xs:element name="complaintIssue" type="xs: String" /> 
                <xs:element name="summary" type="xs: String" /> 
                <xs:element name="attachedDocuments" type="xs: Object" />     
            </xs:all>
        </xs:complexType>
    </xs:element>