<?xml version="1.0" encoding="utf-8" ?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    attributeFormDefault="Unqualified" elementFormDefault="qualified" >
    <xs:element name="TouristAttraction">
        <xs:complexType>
            <xs:all>
                <xs:element name="tourismAttractionName"> 
                    <xs:element name="tourismAttractionNameThai" type="xs: String" /> 
                    <xs:element name="tourismAttractionNameEnglish" type="xs: String" /> 
                </xs:element name="tourismAttractionName"> 
                <xs:element name="superPlace" type="xs: String" /> 
                <xs:element name="subPlace" type="xs: String" /> 
                <xs:element name="contactInformation" > 
                    <xs:element name="addressDetail"> 
                        <xs:element name="tatRegion" type="xs: String" /> 
                        <xs:element name="address" type="xs: String" /> 
                        <xs:element name="alley" type="xs: String" /> 
                        <xs:element name="road" type="xs: String" /> 
                        <xs:element name="subdistrict" type="xs: String" /> 
                        <xs:element name="district" type="xs: String" /> 
                        <xs:element name="province" type="xs: String" />
                        <xs:element name="landmark" type="xs: String" />                     
                    </xs:element name="addressDetail"> 
                    <xs:element name="contactChannel" > 
                        <xs:element name="telephoneNumber" type="xs: String" /> 
                        <xs:element name="email" type="xs: String" /> 
                        <xs:element name="website" type="xs: String" /> 
                        <xs:element name="facebook" type="xs: String" /> 
                        <xs:element name="instragram" type="xs: String" /> 
                        <xs:element name="line" type="xs: String" /> 
                        <xs:element name="tiktok" type="xs: String" /> 
                        <xs:element name="youtube" type="xs: String" /> 
                    </xs:element name="contactChannel"> 
                </xs:element name="contactInformation"> 
                <xs:element name="tourismAttractionCategory" type="xs: String" /> 
                <xs:element name="touristAttractionType" type="xs: String" /> 
                <xs:element name="ownerContactInformation" > 
                    <xs:element name="ownerName" type="xs: String" /> 
                    <xs:element name="ownerTelephoneNumber" type="xs: String" /> 
                    <xs:element name="ownerEmail" type="xs: String" /> 
                </xs:element name="ownerContactInformation"> 
                <xs:element name="businessHour" > 
                    <xs:element name="businessDay" type="xs: String" />
                    <xs:element name="openTime" type="xs: Time" />
                    <xs:element name="closeTime" type="xs: Time" />
                </xs:element name="businessHour" > 
                <xs:element name="attractionDetail" type="xs: String" /> 
                <xs:element name="attractionActivity" type="xs: String" /> 
                <xs:element name="targetGroup" type="xs: String" /> 
                <xs:element name="specificTargetGroup" type="xs: String" />
                <xs:element name="seasonPeriod" > 
                    <xs:element name="highSeasonPeriod" > 
                        <xs:element name="highSeasonFrom" type="xs: Date" /> 
                        <xs:element name="highSeasonTo" type="xs: Date" /> 
                    </xs:element name="highSeasonPeriod" > 
                    <xs:element name="lowSeasonPeriod" > 
                        <xs:element name="lowSeasonFrom" type="xs: Date" /> 
                        <xs:element name="lowSeasonTo" type="xs: Date" /> 
                    </xs:element name="lowSeasonPeriod" > 
                </xs:element name="seasonPeriod" > 
                <xs:element name="ticketPrice" > 
                    <xs:element name="ticketPriceThaiAdult" type="xs: Integer" /> 
                    <xs:element name="ticketPriceThaiChild" type="xs: Integer" /> 
                    <xs:element name="ticketPriceForeignerAdult" type="xs: Integer" /> 
                    <xs:element name="ticketPriceForeignerChild" type="xs: Integer" /> 
                </xs:element name="ticketPrice"> 
                <xs:element name="remark" type="xs: String" /> 
                <xs:element name="transportation" type="xs: String" /> 
                <xs:element name="facility" > 
                    <xs:element name="generalFacility" type="xs: String" /> 
                    <xs:element name="disabledFacility" type="xs: String" /> 
                </xs:element name="facility" > 
                <xs:element name="gpsLocation" > 
                    <xs:element name="latitude" type="xs: Double" /> 
                    <xs:element name="longitude" type="xs: Double" /> 
                </xs:element name="gpsLocation" > 
            </xs:all>
        </xs:complexType>
    </xs:element>