<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Root element -->
  <xs:element name="Document">
    <xs:complexType>
      <xs:sequence>
        <!-- Document Info -->
        <xs:element name="fileReferenceId" type="xs:string"/>
        <xs:element name="fileNameTh" type="xs:string"/>
        <xs:element name="fileNameEn" type="xs:string" minOccurs="0"/>
        <xs:element name="descriptionTh" type="xs:string"/>
        <xs:element name="descriptionEn" type="xs:string" minOccurs="0"/>
        <xs:element name="documentType" type="xs:string"/>
        <xs:element name="reportYear" type="xs:int"/>
        <xs:element name="keywords">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="keyword" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="objective" type="xs:string"/>
        <xs:element name="updateFrequency" type="xs:string"/>
        <xs:element name="dataSource" type="xs:string" minOccurs="0"/>
        <xs:element name="dataCategoryGov" type="xs:string"/>
        <xs:element name="accessCondition" type="xs:string" minOccurs="0"/>
        <xs:element name="creationDate" type="xs:date"/>
        <xs:element name="publicationDate" type="xs:date" minOccurs="0"/>
        <xs:element name="lastUpdateDate" type="xs:date"/>
        <xs:element name="accessUrl" type="xs:anyURI"/>
        <xs:element name="language">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="language" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="documentStatus" type="xs:string"/>
        <xs:element name="underlyingProjectId" type="xs:string" minOccurs="0"/>
        <xs:element name="relatedDatasets" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="relatedDatasets" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="remarks" type="xs:string" minOccurs="0"/>

        <!-- File Info -->
        <xs:element name="File">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="fileFormatMimeType" type="xs:string"/>
              <xs:element name="fileSize" type="xs:string"/>
              <xs:element name="pageCount" type="xs:int" minOccurs="0"/>
              <xs:element name="resolution" type="xs:string" minOccurs="0"/>
              <xs:element name="fileChecksum" type="xs:string" minOccurs="0"/>
              <xs:element name="creatingApplication" type="xs:string" minOccurs="0"/>
              <xs:element name="isSearchablePdf" type="xs:boolean" minOccurs="0"/>
              <xs:element name="fileObject" type="xs:base64Binary" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- Organization Info -->
        <xs:element name="Organization">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="owningOrganization" type="xs:string"/>
              <xs:element name="responsibleDivision" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- Contact Info -->
        <xs:element name="Contact" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="responsibleDivisionEmail" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- License Info -->
        <xs:element name="License">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="license" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>